CrudMvcConsumeAPI/Models/AgentViewModel.cs
using System.ComponentModel.DataAnnotations;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace CrudMvcConsumeAPI.Models
{
    public class AgentViewModel
    {
        [Key]
        public int ID { get; set; }
        public DateTime RegDate { get; set; }
        public string RegStatus { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string BirthPlace { get; set; }
        public DateTime BirthDate { get; set; }
        public string Address { get; set; }

        [DataType(DataType.EmailAddress)]
        //[EmailAddress]
        public string Email { get; set; }
        public string Phone { get; set; }
        public string IdCard { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }

        [MinLength(8)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$",
            ErrorMessage = "Password setidaknya mengandung satu huruf kapital," +
            "satu huruf kecil, satu angka dan tidak mengandung karakter khusus " +
            "(misalnya: !, @, #, $).")]
        //[DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

CrudMvcConsumeAPI/Models/ErrorViewModel.cs
namespace CrudMvcConsumeAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudMvcConsumeAPI/Controllers/AgentController.cs
using CrudMvcConsumeAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace CrudMvcConsumeAPI.Controllers
{
    public class AgentController : Controller
    {
        Uri baseAddress = new Uri("http://localhost:5269/api");
        private readonly HttpClient _client;

        public AgentController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }

        [HttpGet]
        public IActionResult IndexAgent()
        {
            List<AgentViewModel> agentList = new List<AgentViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/" +
                "agent/GetAll").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                agentList = JsonConvert.DeserializeObject<List<AgentViewModel>>(data);
            }

            return View(agentList);
        }

        [HttpGet]
        public IActionResult Create()
        { 
            return View(); 
        }

        [HttpPost]
        public IActionResult Create(AgentViewModel agent)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string data = JsonConvert.SerializeObject(agent);
                StringContent content = new StringContent(data, Encoding.UTF8,
                    "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/" +
                    "agent/Post", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["SuccessMsg"] = "Added agent successfully";
                    return RedirectToAction("IndexAgent");
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Couldn't added new agent!";
                return View();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                AgentViewModel agent = new AgentViewModel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/" +
                    "agent/GetById/" + id).Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    agent = JsonConvert.DeserializeObject<AgentViewModel>(data);
                }
                return View(agent);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(AgentViewModel model)
        {
            try
            {
                string data = JsonConvert.SerializeObject(model);
                StringContent content = new StringContent(data, Encoding.UTF8,
                        "application/json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/" +
                        "agent/Update", content).Result;

                if (response.IsSuccessStatusCode)
                {
                    TempData["SuccessMsg"] = "Agent details updated";
                    return RedirectToAction("IndexAgent");
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id) 
        {
            try
            {
                AgentViewModel agent = new AgentViewModel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/" +
                    "agent/GetById/" + id).Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    agent = JsonConvert.DeserializeObject<AgentViewModel>(data);
                }
                return View(agent);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + "/Agent/Delete/" 
                    + id).Result;

                if (response.IsSuccessStatusCode)
                {
                    TempData["SuccessMsg"] = "Agent details deleted";
                    return RedirectToAction("IndexAgent");
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

            return View();
        }

    }
}

CrudMvcConsumeAPI/Controllers/HomeController.cs
using CrudMvcConsumeAPI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudMvcConsumeAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudMvcConsumeAPI/Views/Agent/Create.cshtml
@model CrudMvcConsumeAPI.Models.AgentViewModel
@{
    //Layout = "_Layout";
}
<html>
<head>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">

    <style>
        .custom-icon {
            width: 20px; /* Atur lebar ikon sesuai kebutuhan */
            height: auto; /* Biarkan ketinggian mengikuti proporsi aslinya */
        }
    </style>
</head>
</html>

<div class="mt-2" style="width:80%">

    @if (TempData["errorMessage"] != null)
    {
        <div class="mb-3">
            @TempData["errorMessage"]
        </div>
    }

    @if ((string)TempData["SuccessMsg"] == "Added successfully")
    {
        <div class="alert alert-success">
            <strong>Congrats. Your data has been successfully saved</strong>
        </div>
    }

    <form asp-action="Create">
        <h2>CREATE AGENT</h2>

        <div class="container">
            <div class="row">

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="RegDate" class="form-label" style="font-weight: bold;">REGISTRATION DATE</label>
                        <input asp-for="RegDate" type="date" class="form-control" placeholder="Registration Date" />
                        <span class="text-danger" asp-validation-for="RegDate"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="RegStatus" class="form-label" style="font-weight: bold;">REGISTRATION STATUS</label>
                        <input asp-for="RegStatus" type="text" class="form-control" placeholder="Registration Status" />
                        <span class="text-danger" asp-validation-for="RegStatus"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="Name" class="form-label" style="font-weight: bold;">NAME</label>
                        <input asp-for="Name" type="text" class="form-control" placeholder="FullName" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="Gender" class="form-label" style="font-weight: bold;">GENDER</label>
                        <input asp-for="Gender" type="text" class="form-control" placeholder="Gender" />
                        <span class="text-danger" asp-validation-for="Gender"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="BirthPlace" class="form-label" style="font-weight: bold;">BIRTH PLACE</label>
                        <input asp-for="BirthPlace" type="text" class="form-control" placeholder="BirthPlace" />
                        <span class="text-danger" asp-validation-for="BirthPlace"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="BirthDate" class="form-label" style="font-weight: bold;">BIRTH DATE</label>
                        <input asp-for="BirthDate" type="date" class="form-control" />
                        <span class="text-danger" asp-validation-for="BirthDate"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="Address" class="form-label" style="font-weight: bold;">ADDRESS</label>
                        <input asp-for="Address" type="text" class="form-control" placeholder="Address" />
                        <span class="text-danger" asp-validation-for="Address"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="Email" class="form-label" style="font-weight: bold;">EMAIL</label>
                        <input asp-for="Email" type="text" class="form-control" placeholder="Email" />
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="Phone" class="form-label" style="font-weight: bold;">PHONE</label>
                        <input asp-for="Phone" type="text" class="form-control" placeholder="Phone" />
                        <span class="text-danger" asp-validation-for="Phone"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="IdCard" class="form-label" style="font-weight: bold;">IDCARD</label>
                        <input asp-for="IdCard" type="text" class="form-control" placeholder="IdCard" />
                        <span class="text-danger" asp-validation-for="IdCard"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="CreatedDate" class="form-label" style="font-weight: bold;">CREATED DATE</label>
                        <input asp-for="CreatedDate" type="date" class="form-control" placeholder="CreatedDate" />
                        <span class="text-danger" asp-validation-for="CreatedDate"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="CreatedBy" class="form-label" style="font-weight: bold;">CREATED BY</label>
                        <input asp-for="CreatedBy" type="text" class="form-control" placeholder="CreatedBy" />
                        <span class="text-danger" asp-validation-for="CreatedBy"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <label asp-for="Password" class="form-label" style="font-weight: bold;">PASSWORD</label>
                    <div class="input-group">
                        <input asp-for="Password" type="password" class="form-control" placeholder="Password" />
                        <span class="input-group-text toggle-password" onclick="togglePassword()">
                            <i class="bi bi-eye custom-icon"></i>
                        </span>
                    </div>
                    <span class="text-danger" asp-validation-for="Password"></span>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary" style="font-weight: bold;">Submit</button>
                    <a href="/Agent/IndexAgent" class="btn btn-primary" style="font-weight: bold;">Back</a>
                </div>

            </div>
        </div>
    </form>
</div>

<script>
    function togglePassword() {
        var passwordInput = document.getElementById("Password");
        var eyeIcon = document.querySelector('.toggle-password i');

        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            eyeIcon.classList.remove('bi-eye');
            eyeIcon.classList.add('bi-eye-slash');
        } else {
            passwordInput.type = "password";
            eyeIcon.classList.remove('bi-eye-slash');
            eyeIcon.classList.add('bi-eye');
        }
    }
</script>

CrudMvcConsumeAPI/Views/Agent/Delete.cshtml
@model CrudMvcConsumeAPI.Models.AgentViewModel

@{
    ViewData["Title"] = "Delete";
}

@*<h1>Delete</h1>*@

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>AgentViewModel</h4>*@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthPlace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthPlace)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCard)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="IndexAgent">Back to List</a>
    </form>
</div>

CrudMvcConsumeAPI/Views/Agent/Edit.cshtml
@model CrudMvcConsumeAPI.Models.AgentViewModel
@{
}

<html>
<head>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">

    <style>
        .custom-icon {
            width: 20px; /* Atur lebar ikon sesuai kebutuhan */
            height: auto; /* Biarkan ketinggian mengikuti proporsi aslinya */
        }
    </style>
</head>
</html>

<div class="mt-2" style="width:80%">

    @if (TempData["errorMessage"] != null)
    {
        <div class="mb-3">
            @TempData["errorMessage"]
        </div>
    }

    @if ((string)TempData["SuccessMsg"] == "Agent details update successfully")
    {
        <div class="alert alert-success">
            <strong>Congrats. Your data has been successfully updated</strong>
        </div>
    }

    <form asp-action="Edit">
        <input asp-for="ID" type="hidden" class="form-control">
        <h2>EDIT AGENT</h2>

        <div class="container">
            <div class="row">

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="RegDate" class="form-label" style="font-weight: bold;">REGISTRATION DATE</label>
                        <input asp-for="RegDate" type="date" class="form-control" />
                        <span class="text-danger" asp-validation-for="RegDate"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="RegStatus" class="form-label" style="font-weight: bold;">REGISTRATION STATUS</label>
                        <input asp-for="RegStatus" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="RegStatus"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="Name" class="form-label" style="font-weight: bold;">NAME</label>
                        <input asp-for="Name" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="Gender" class="form-label" style="font-weight: bold;">GENDER</label>
                        <input asp-for="Gender" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="Gender"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="BirthPlace" class="form-label" style="font-weight: bold;">BIRTH PLACE</label>
                        <input asp-for="BirthPlace" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="BirthPlace"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="BirthDate" class="form-label" style="font-weight: bold;">BIRTH DATE</label>
                        <input asp-for="BirthDate" type="date" class="form-control" />
                        <span class="text-danger" asp-validation-for="BirthDate"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="Address" class="form-label" style="font-weight: bold;">ADDRESS</label>
                        <input asp-for="Address" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="Address"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="Email" class="form-label" style="font-weight: bold;">EMAIL</label>
                        <input asp-for="Email" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="Phone" class="form-label" style="font-weight: bold;">PHONE</label>
                        <input asp-for="Phone" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="Phone"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="IdCard" class="form-label" style="font-weight: bold;">ID CARD</label>
                        <input asp-for="IdCard" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="IdCard"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <label asp-for="CreatedDate" class="form-label" style="font-weight: bold;">CREATED DATE</label>
                        <input asp-for="CreatedDate" type="date" class="form-control" />
                        <span class="text-danger" asp-validation-for="CreatedDate"></span>
                    </div>
                    <div class="col-md-6">
                        <label asp-for="CreatedBy" class="form-label" style="font-weight: bold;">CREATED BY</label>
                        <input asp-for="CreatedBy" type="text" class="form-control" />
                        <span class="text-danger" asp-validation-for="CreatedBy"></span>
                    </div>
                </div>

                <div class="row mb-4">
                    <label asp-for="Password" class="form-label" style="font-weight: bold;">PASSWORD</label>
                    <div class="input-group">
                        <input asp-for="Password" type="text" class="form-control" />
                        <span class="input-group-text toggle-password" onclick="togglePassword()">
                            <i class="bi bi-eye custom-icon"></i>
                        </span>
                    </div>
                    <span class="text-danger" asp-validation-for="Password"></span>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary" style="font-weight: bold;">Update</button>
                    <a href="/Agent/IndexAgent" class="btn btn-primary" style="font-weight: bold">Back</a>
                </div>

            </div>
        </div>
    </form>
</div>

<script>
    function togglePassword() {
        var passwordInput = document.getElementById("Password");
        var eyeIcon = document.querySelector('.toggle-password i');

        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            eyeIcon.classList.remove('bi-eye');
            eyeIcon.classList.add('bi-eye-slash');
        } else {
            passwordInput.type = "password";
            eyeIcon.classList.remove('bi-eye-slash');
            eyeIcon.classList.add('bi-eye');
        }
    }
</script>

CrudMvcConsumeAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudMvcConsumeAPI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/Agent/IndexAgent" style="font-weight: bold">INDEX AGENT</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>


@*<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>@ViewData["Title"] - MandiriTechTestWebConsumeAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MandiriTechTestWebConsumeAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MandiriTechTestWebConsumeAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agent" asp-action="IndexAgent">Index Agent</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MandiriTechTestWebConsumeAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>*@